### ISSUE TITLE
Object is not specified

### ISSUE THREAD

**Issue by Oktai15** [huggingface/pytorch-openai-transformer-lm#13]
https://github.com/huggingface/pytorch-openai-transformer-lm/blob/37e77aff19431b0b9c5b5a411ad71bcc2e138ffd/model_pytorch.py#L180

**Comment by rodgzilla** [comment]
The problem should now be fixed.

**Comment by teucer** [comment]
@rodgzilla could you please tell how to use  `LMHead ` with an explicit code example to e.g. train a text similarity model...

**Comment by rodgzilla** [comment]
You can probably figure this out by yourself by reading the [research paper](https://s3-us-west-2.amazonaws.com/openai-assets/research-covers/language-unsupervised/language_understanding_paper.pdf) and adapting the task specific code from `train.py`.

**Comment by thomwolf** [comment]
Thanks for fixing that @rodgzilla!
