### ISSUE TITLE
a git clone is large because history has the "add model" commit

### ISSUE THREAD

**Issue by soumith** [huggingface/pytorch-openai-transformer-lm#3]
Since git works on cloning entire history, and since you did not "squash and merge" the PR https://github.com/huggingface/pytorch-openai-transformer-lm/pull/1

what is happening is that a fresh `git clone` is 400MB now, and in the git history, the model is included.

I suggest the following:
- rebase so that the 3 commits a7ed, 368b and 341b are squashed, and then force-push to master.

Here's how you can do this:

- git rebase -i aa800ef759275b575db324db5e6194c50488de57
- Then replace "pick" with "s" in the commit entries for 341b and 368b
- Exit the editor.

Then do: `git push origin HEAD:master --force`

**Comment by thomwolf** [comment]
Done! thanks a lot @soumith for the detailed steps!
