### ISSUE TITLE
finetuning the model for NLI, but using sentence embeddings instead of word embeddings

### ISSUE THREAD

**Issue by saurabhvyas** [huggingface/pytorch-openai-transformer-lm#30]
Is it possible to use the pretrained model, and finetune on NLI task on my dataset, but using sentence vectors instead of word vectors, because the length of premise para can be very big ( 1500 words ) ?

**Comment by rodgzilla** [comment]
I do not think that this approach would work. The embedding that is used by the network have been trained along all the other weights and can therefore not be easily replaced.

One thing you could try is to "fake" a sentence embedding using the pre-trained word embeddings of the network. You could compute the embedding of some sentences as a simple mean of its word vectors ([or a closely related variant](https://openreview.net/pdf?id=SyK00v5xx)). As this average "lives" in the same space as the word vectors, the network may be able to work with it.

If I wanted to do something like you describe, I would feed the network a sequence which starts with sentence embeddings and ends with word embeddings if I thought that the end of the premise contains more important informations.

The main issue with this approach is that the network is loosing the ability to attend to specific words.

I would be really interested to know if the approach that I am describing is working. Could you let us know if it is the case?

**Comment by saurabhvyas** [comment]
@rodgzilla Thanks for your reply, I have this project in my mind, and I might try your idea, however right now I am using some other model for what I am trying to do, I will definitely update here, if it works.
