### ISSUE TITLE
Pre-trained LMHead

### ISSUE THREAD

**Issue by rodgzilla** [huggingface/pytorch-openai-transformer-lm#7]
Hi!

First, I would like to thank you for your translation of the implementation of this paper.

I have read the code and managed to run it but I am not able to find how to load pre-trained weights into a LMHead to get a general English language model. Did the openAI guys not release the weights of this final layer? 

I thought the performance would be better starting the finetuning process from a pre-trained LMHead.

**Comment by soskek** [comment]
The model uses a single word embedding matrix for input to the transformer and output matrix (LMHead), as shown in Eq. (2) in [the paper](https://s3-us-west-2.amazonaws.com/openai-assets/research-covers/language-unsupervised/language_understanding_paper.pdf).
Following that, this code also use the word embedding matrix which is loaded only once.

**Comment by rodgzilla** [comment]
I missed this part in the paper, I'm going to read it again.

Thanks a lot for your quick answer.

**Comment by thomwolf** [comment]
Thanks @soskek!
